version: '3.8'
services:
  web:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 7s
        max_attempts: 3
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.app
      - FLASK_RUN_HOST=0.0.0.0
      - DB_HOST=db  # Use the service name as the host
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=kapo
    depends_on:
      - db  # Ensure the db service starts before the Flask app
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kapo
    ports:
      - "5432:5432"