version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.app
      - FLASK_RUN_HOST=0.0.0.0
      - DB_HOST=
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=kapo